"""
alembic/env.py
─────────────────────────────────────────────────────────────
Alembic environment configuration.

Key responsibilities
────────────────────
1. Inject the database URL from `Settings` (not alembic.ini)
2. Import Base + all models so autogenerate detects schema changes
3. Support both "online" (live DB) and "offline" (SQL script) modes
4. Configure compare_type=True so column type changes are detected

Running migrations
──────────────────
  # Generate a new migration after changing models
  alembic revision --autogenerate -m "add vendor country column"

  # Apply all pending migrations
  alembic upgrade head

  # Roll back one migration
  alembic downgrade -1
"""

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# ── Make `backend` importable from the project root ──────────────────────────
# Alembic runs from the project root; add it to sys.path explicitly.
PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# ── Import application components ─────────────────────────────────────────────
from backend.config import get_settings
from backend.database import Base  # noqa: F401

# IMPORTANT: Import ALL models here so SQLAlchemy registers them on Base.metadata
# before Alembic inspects it. Failure to import a model means its table will
# NOT be included in autogenerated migrations.
import backend.models  # noqa: F401 – triggers __init__.py which imports all models

# ─────────────────────────────────────────────────────────────────────────────
settings = get_settings()

# Alembic Config object – provides access to values in alembic.ini
config = context.config

# Inject the database URL from our Settings class
# This overrides the blank `sqlalchemy.url` in alembic.ini
config.set_main_option("sqlalchemy.url", settings.database_url)

# Set up Python logging from the alembic.ini [loggers] section
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The metadata object that Alembic inspects for autogenerate
target_metadata = Base.metadata


# ─────────────────────────────────────────────────────────────────────────────
# Offline mode – generates a SQL script without touching the DB
# ─────────────────────────────────────────────────────────────────────────────

def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    Generates a SQL script that can be reviewed and applied manually.
    Useful for production deployments where DBA approval is required.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,           # Detect column type changes
        compare_server_default=True, # Detect server default changes
    )

    with context.begin_transaction():
        context.run_migrations()


# ─────────────────────────────────────────────────────────────────────────────
# Online mode – applies migrations directly to a live database
# ─────────────────────────────────────────────────────────────────────────────

def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    Connects to the database and applies pending migrations directly.
    Used for development and CI/CD pipelines.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # No connection pooling during migrations
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            # Render enums as their native PostgreSQL ENUM types
            include_schemas=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# ─────────────────────────────────────────────────────────────────────────────
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
